### ISSUE TITLE
Migrate fresh

### ISSUE THREAD

**Issue by TheAaronLawrence** [x7media/laravel-planetscale#4]
Noticed this option to migrate fresh wasn't an option, is that intended? `php artisan pscale:migrate:fresh` Very much needed when developing fresh applications.

**Comment by dennissvu** [comment]
+1

**Comment by ryanshipswell** [comment]
That's a very destructive thing to do to a production database, I'm not sure why you'd want to do that, but in that case you can just delete the current branch and start over with a new one.
